### ISSUE TITLE
Wii sport resort friend code 0000-000-0000 bug

### ISSUE THREAD

**Issue by Mkwiiripper** [RiiConnect24/CMOC-Server#1]
I played wii sports resort but when i click the mii conntest channel icon to view the friend code i get 0000-000-0000 why is is happening?

**Comment by ghost** [comment]
they don't know how to fix it yet.

**Comment by Mkwiiripper** [comment]
But shutterbug2000 knows how to fix this

**Comment by Mkwiiripper** [comment]
But is bussy with the school

**Comment by ghost** [comment]
...he didn't even finish CMOC, Josh did.

**Comment by Mkwiiripper** [comment]
But shutterbug2000 descrypted the file and from 3 moths hard work the find the file structure withaout shutterbug2000 josh wil not be working on the mii contest channel

**Comment by ghost** [comment]
but still, they don't even know how to get the code to display on screen

**Comment by larsenv** [comment]
🤦‍♂️

Eri Kiorai being himself again. Josh purposely set it to 0000-0000-0000 because we don't know the algorithm to generate the 12-digit entry number. Internally, a simple number is used that's smaller than a 12-digit number. That somehow is converted to the 12-digit number, but we don't know how.

Also, Shutterbug has nothing to do with this. He's working on other projects right now.

**Comment by Mkwiiripper** [comment]
Ok @larsenv thanks for the info i din't know that and yes i know that shutterbug2000 is working on other project as allawys nice jobs for cmoc hard work
